### PR TITLE
Improve Arabic messages

### PR DESCRIPTION
**Pull request by ebraminio**
Just simple and minor orthography fixes in Arabic messages and adding missing markup and punctuations that exists in English messages but not in Arabic ones.

Also adds Arabic long vowels to vowels list to make character's mouth move in Arabic. 

While reviewing please note that as Arabic is written from right to left the space before comma is on its right not left so I've removed the one on its right (before) not left that might be confusing to the reviewer but not someone who uses the script everyday.

### CODE REVIEW

**Comment by ebraminio** [comment]
Also is it okay to add another language here?

**Comment by NathanLovato** [comment]
Thank you for the contribution! Much appreciated.
Regarding adding another language, we'd prefer not to add more, as this demo aims to show the support for one latin script, one CJK language, and one right-to-left language.

**Comment by NathanLovato** [comment]
GitHub seems to be having some issues at the moment. I can´t merge the PR or push changes right now. I'll try again later.

**Comment by ebraminio** [comment]
Oh, I almost have forgot this, thanks for considering this 😊

> Regarding adding another language, we'd prefer not to add more

That's totally understandable.

> GitHub seems to be having some issues at the moment. I can´t merge the PR or push changes right now. I'll try again later.

I can rebase if you think is needed. Thanks 😊

**Pull request merged**
